scripts: add some assertions to etcd backup code
Starting with `containerd` 1.4.1, the 'v2' runtime is used. This changes
the paths used under `/run/containerd`. This patch prepares to support
these various options, and adds a couple of assertions to bail out when
certain expectations are not met.

diff --git a/scripts/backup.sh.in b/scripts/backup.sh.in
--- a/scripts/backup.sh.in
+++ b/scripts/backup.sh.in
@@ -184,8 +184,22 @@ backup_etcd() {
         --state Running)"
     echo "Running '${cmd[*]}' in etcd container $etcd_container"
     crictl exec -i "$etcd_container" sh -c "${cmd[*]}"
+
+    local -r rootfs_v1="/run/containerd/io.containerd.runtime.v1.linux/k8s.io/${etcd_container}/rootfs"
+    local rootfs=''
+    if test -d "${rootfs_v1}"; then
+        rootfs="${rootfs_v1}"
+    else
+        die "Unable to find etcd container rootfs"
+    fi
+
+    local -r snapshot_file="${rootfs}/${etcd_snapshot}"
+    if ! test -f "${snapshot_file}"; then
+        die "etcd snapshot file not found"
+    fi
+
     _save_cp \
-        "/run/containerd/io.containerd.runtime.v1.linux/k8s.io/${etcd_container}/rootfs/${etcd_snapshot}" \
+        "${snapshot_file}" \
         "${BACKUP_DIR}/etcd_snapshot"
 }
 
