bootstrap: add `--verbose` option
See: https://github.com/scality/metalk8s/pull/1032#pullrequestreview-230617371

diff --git a/scripts/bootstrap.sh.in b/scripts/bootstrap.sh.in
--- a/scripts/bootstrap.sh.in
+++ b/scripts/bootstrap.sh.in
@@ -7,6 +7,28 @@ set -u
 # support `-o pipefail` (though must support `-e` and `-u` per POSIX).
 if test -z "$(type -p)"; then set -o pipefail; fi
 
+VERBOSE=${VERBOSE:-0}
+
+if ! options=$(getopt --options v --long verbose -- "$@"); then
+    echo 1>&2 "Incorrect arguments provided"
+    exit 1
+fi
+eval set -- "$options"
+
+while true; do
+    case "$1" in
+        -v|--verbose)
+            VERBOSE=1;
+            shift;;
+        --)
+            shift;
+            break;;
+        *)
+            echo 1>&2 "Option parsing failure";
+            exit 1;;
+    esac
+done
+
 TMPFILES=$(mktemp -d)
 
 cleanup() {
@@ -37,7 +59,7 @@ declare -A GPGCHECK_REPOSITORIES=(
     [metalk8s-scality]=0
 )
 
-run() {
+run_quiet() {
     local name=$1
     shift 1
 
@@ -80,6 +102,21 @@ EOM
     fi
 }
 
+run_verbose() {
+    local name=$1
+    shift 1
+
+    echo "> ${name}..."
+    "$@"
+}
+
+run() {
+    if [ "$VERBOSE" -eq 1 ]; then
+        run_verbose "${@}"
+    else
+        run_quiet "${@}"
+    fi
+}
 
 die() {
     echo 1>&2 "$@"
