ci: Refactor Eve YAML description
Our `eve/main.yml` build description was becoming too repetitive,
involving numerous subtle differences between similar stages (e.g.
between `single-node-upgrade` and `single-node-downgrade`)

A better solution in the future will be to generate this YAML file from
a "real" programming language, using some homemade DSL.

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -5,6 +5,188 @@ branches:
   user/*, feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*, dependabot/*:
     stage: pre-merge
 
+models:
+  # --- Re-usable steps (no parameters) ---
+  - Git: &git_pull
+      name: git pull
+      repourl: "%(prop:git_reference)s"
+      method: clobber
+      retryFetch: true
+      haltOnFailure: true
+  - ShellCommand: &setup_cache
+      name: Setup proxy cache
+      command: >
+          curl -s http://proxy-cache/setup.sh | sudo sh &&
+          . /usr/local/bin/use_scality_proxy_cache
+      haltOnFailure: true
+  - ShellCommand: &wait_for_docker
+      name: Wait for Docker daemon to be ready
+      command: |
+        bash -c '
+        for i in {1..150}
+        do
+          docker info &> /dev/null && exit
+          sleep 2
+        done
+        echo "Could not reach Docker daemon from buildbot worker" >&2
+        exit 1'
+      haltOnFailure: true
+  - ShellCommand: &build_all
+      name: Build everything
+      env:
+        PYTHON_SYS: python3.6
+      # There are 3 CPUs available for Docker, and 1 for `doit` in the Pod.
+      # Given the network IO-bound nature of some of the build steps, and
+      # most build steps running in Docker, set concurrency to 4.
+      command: ./doit.sh -n 4
+      usePTY: true
+      haltOnFailure: true
+  - ShellCommand: &ssh_ip_setup
+      name: Report IP and install SSH keys
+      command: >
+        ip a &&
+        mkdir -p ~/.ssh &&
+        echo "%(secret:ssh_pub_keys)s" >> ~/.ssh/authorized_keys
+  - ShellCommand: &check_iso_checksum
+      name: Check image with checksum
+      command: sha256sum -c SHA256SUM
+      haltOnFailure: true
+  - Upload: &upload_artifacts
+      name: Upload artifacts
+      source: artifacts
+  - Upload: &upload_report_artifacts
+      name: Upload sosreport logs to artifacts
+      source: sosreport
+  - ShellCommand: &collect_sosreport
+      name: Collect logs using sosreport
+      command: >
+        sudo sosreport --all-logs
+        -o metalk8s -kmetalk8s.podlogs=True
+        -o containerd -kcontainerd.all=True -kcontainerd.logs=True
+        --batch --tmp-dir /var/tmp &&
+        sudo chown eve:eve /var/tmp/sosreport*
+  - ShellCommand: &wait_debug
+      name: Debug step - wait befor allowing resource destruction
+      timeout: 3600
+      command: sleep 3600
+      doStepIf: false
+      alwaysRun: true
+
+  # --- Re-usable steps (with parameters) ---
+  - SetPropertyFromCommand: &set_version_prop
+      name: Set version as property from built artifacts
+      property: metalk8s_version
+      env:
+        BASE_URL: "%(prop:artifacts_private_url)s"
+      command: >
+        bash -c '
+        . <(curl -s "${BASE_URL}/product.txt") &&
+        echo $VERSION'
+  - ShellCommand: &copy_artifacts
+      name: Put the artifacts to upload in a separate directory
+      env: &_env_copy_artifacts
+        DEST_DIR: "artifacts"
+        ARTIFACTS: >-
+          _build/metalk8s.iso
+          _build/SHA256SUM
+          _build/root/product.txt
+      command: |
+        bash -c '
+        mkdir "${DEST_DIR}" -p
+        for artifact in ${ARTIFACTS}; do
+          cp "$artifact" "${DEST_DIR}"
+        done'
+      haltOnFailure: true
+  - ShellCommand: &copy_report_artifacts
+      name: Put the sosreport logs to upload in a separate directory
+      env:
+        DEST_DIR: sosreport/sosreport
+      command: mkdir -p "${DEST_DIR}" && cp /var/tmp/sosreport* "${DEST_DIR}"
+      alwaysRun: true
+  - ShellCommand: &retrieve_iso
+      name: Retrieve ISO image
+      env:
+        BASE_URL: "%(prop:artifacts_private_url)s"
+        DEST_DIR: "."
+      command: >
+        curl -s -XGET -o "${DEST_DIR}/metalk8s.iso" "${BASE_URL}/metalk8s.iso"
+      haltOnFailure: true
+  - ShellCommand: &retrieve_iso_checksum
+      <<: *retrieve_iso
+      name: Retrieve ISO image checksum
+      command: >
+        curl -s -XGET -o "${DEST_DIR}/SHA256SUM" "${BASE_URL}/SHA256SUM"
+  - ShellCommand: &create_mountpoint
+      name: Create mountpoint
+      env:
+        PRODUCT_VERSION: "%(prop:metalk8s_version)s"
+      command: sudo mkdir -p "/srv/scality/metalk8s-${PRODUCT_VERSION}"
+  - ShellCommand: &mount_iso
+      name: Mount ISO image
+      env:
+        ISO_PATH: metalk8s.iso
+        PRODUCT_VERSION: "%(prop:metalk8s_version)s"
+      command: >
+        sudo mount -o loop "${ISO_PATH}"
+        "/srv/scality/metalk8s-${PRODUCT_VERSION}"
+  - ShellCommand: &bootstrap_config
+      name: Create bootstrap configuration file
+      env:
+        PRODUCT_VERSION: "%(prop:metalk8s_version)s"
+      command: |
+        sudo bash << EOF
+        mkdir -p /etc/metalk8s
+        cat > /etc/metalk8s/bootstrap.yaml << END
+        apiVersion: metalk8s.scality.com/v1alpha2
+        kind: BootstrapConfiguration
+        networks:
+          controlPlane: 10.100.0.0/16
+          workloadPlane: 10.100.0.0/16
+        ca:
+          minion: $(hostname)
+        apiServer:
+          host: $(ip route get 10.100.0.0 | awk '/10.100.0.0/{ print $6 }')
+        archives:
+          - "/srv/scality/metalk8s-${PRODUCT_VERSION}"
+        END
+        EOF
+      haltOnFailure: true
+  - ShellCommand: &run_bootstrap
+      name: Start the bootstrap process
+      env:
+        PRODUCT_VERSION: "%(prop:metalk8s_version)s"
+      command: >
+        sudo bash
+        "/srv/scality/metalk8s-${PRODUCT_VERSION}/bootstrap.sh"
+        --verbose
+      haltOnFailure: true
+  - ShellCommand: &local_tests
+      name: Run tests locally
+      env: &_env_local_tests
+        BRANCH: "%(prop:branch)s"
+        ISO_MOUNTPOINT: "/srv/scality/metalk8s-%(prop:metalk8s_version)s"
+        PYTEST_FILTERS: "post and ci and not multinodes"
+      command: >
+        git checkout "${BRANCH}" &&
+        tox -e tests-local -- -m "${PYTEST_FILTERS}"
+      haltOnFailure: true
+  - ShellCommand: &bastion_tests
+      name: Run tests on Bastion
+      env: &_env_bastion_tests
+        SSH_CONFIG_FILE: "/home/centos/ssh_config"
+        ISO_MOUNTPOINT: "/var/tmp/metalk8s"
+        TEST_HOSTS_LIST: "bootstrap"
+        PYTEST_FILTERS: "post and ci"
+      command: >
+        ssh -F ssh_config bastion --
+        "cd metalk8s &&
+        export SSH_CONFIG_FILE=\"${SSH_CONFIG_FILE}\" &&
+        export ISO_MOUNTPOINT=\"${ISO_MOUNTPOINT}\" &&
+        export TEST_HOSTS_LIST=\"${TEST_HOSTS_LIST}\" &&
+        tox -e tests -- -m \"${PYTEST_FILTERS}\""
+      workdir: build/eve/workers/openstack-multiple-nodes/terraform/
+      haltOnFailure: true
+
 stages:
   pre-merge:
     worker:
@@ -17,13 +199,7 @@ stages:
             - docs
             - lint
           haltOnFailure: true
-      - SetPropertyFromCommand:
-          name: Set version as property from built artifacts
-          property: metalk8s_version
-          command: >
-            bash -c '
-            . <(curl -s "%(prop:artifacts_private_url)s/product.txt") &&
-            echo $VERSION'
+      - SetPropertyFromCommand: *set_version_prop
       - TriggerStages:
           name: Trigger single-node and multiple-nodes steps with built ISO
           stage_names:
@@ -31,59 +207,26 @@ stages:
             - multiple-nodes
 
   build:
-    worker:
+    worker: &build_worker
       type: kube_pod
       path: eve/workers/pod-builder/pod.yaml
       images:
         docker-builder: eve/workers/pod-builder
     steps:
+      - ShellCommand: *wait_for_docker
+      - Git: *git_pull
+      - ShellCommand: *setup_cache
+      - ShellCommand: *build_all
       - ShellCommand:
-          name: Wait for Docker daemon to be ready
-          command: |
-            bash -c '
-            for i in {1..150}
-            do
-              docker info &> /dev/null && exit
-              sleep 2
-            done
-            echo "Could not reach Docker daemon from buildbot worker" >&2
-            exit 1'
-          haltOnFailure: true
-      - Git: &git_pull
-          name: git pull
-          repourl: "%(prop:git_reference)s"
-          method: clobber
-          retryFetch: true
-          haltOnFailure: true
-      - ShellCommand: &setup_cache
-          name: Setup proxy cache
-          command: >
-              curl -s http://proxy-cache/setup.sh | sudo sh &&
-              . /usr/local/bin/use_scality_proxy_cache
-          haltOnFailure: true
-      - ShellCommand:
-          name: build everything
+          <<: *copy_artifacts
           env:
-            PYTHON_SYS: python3.6
-          # There are 3 CPUs available for Docker, and 1 for `doit` in the Pod.
-          # Given the network IO-bound nature of some of the build steps, and
-          # most build steps running in Docker, set concurrency to 4.
-          command: ./doit.sh -n 4
-          usePTY: true
-          haltOnFailure: true
-      - ShellCommand:
-          name: Put the iso file in a separate folder
-          command: >
-            mkdir iso &&
-            cp _build/metalk8s.iso _build/SHA256SUM _build/root/product.txt iso
-          haltOnFailure: true
-      - Upload:
-          name: upload artifacts
-          source: iso/
-          urls:
-            - "*.iso"
-            - SHA256SUM
-            - product.txt
+            <<: *_env_copy_artifacts
+            ARTIFACTS: >-
+              build.log
+              _build/metalk8s.iso
+              _build/SHA256SUM
+              _build/root/product.txt
+      - Upload: *upload_artifacts
 
   docs:
     worker:
@@ -133,110 +276,42 @@ stages:
     steps:
       - Git: *git_pull
       - ShellCommand: *setup_cache
-      - ShellCommand: &ssh_ip_setup
-          name: Report IP and install SSH keys
-          command: >
-            ip a &&
-            mkdir -p ~/.ssh &&
-            echo "%(secret:ssh_pub_keys)s" >> ~/.ssh/authorized_keys
-      - ShellCommand: &retrieve_iso
-          name: Retrieve ISO image
-          command: >
-            curl -s -XGET -o metalk8s.iso
-            "%(prop:artifacts_private_url)s/metalk8s.iso"
-          haltOnFailure: true
-      - ShellCommand: &retrieve_iso_checksum
-          name: Retrieve ISO image checksum
-          command: >
-            curl -s -XGET -o SHA256SUM
-            "%(prop:artifacts_private_url)s/SHA256SUM"
-          haltOnFailure: true
-      - ShellCommand: &check_iso_checksum
-          name: Check image with checksum
-          command: sha256sum -c SHA256SUM
-          haltOnFailure: true
+      - ShellCommand: *ssh_ip_setup
+      # --- Retrieve ISO ---
+      - ShellCommand: *retrieve_iso
+      - ShellCommand: *retrieve_iso_checksum
+      - ShellCommand: *check_iso_checksum
+      # --- Prepare for Bootstrap ---
+      - ShellCommand: *create_mountpoint
+      - ShellCommand: *mount_iso
+      - ShellCommand: *bootstrap_config
+      # --- Install ---
+      - ShellCommand: *run_bootstrap
+      # --- Test ---
+      - ShellCommand: &fast_tests
+          <<: *local_tests
+          name: Run fast tests locally
+          env: &_env_fast_tests
+            <<: *_env_local_tests
+            PYTEST_FILTERS: "post and ci and not multinodes and not slow"
       - ShellCommand:
-          name: Create mountpoint
-          command: >
-            sudo mkdir -p /srv/scality/metalk8s-%(prop:metalk8s_version)s
-      - ShellCommand:
-          name: Mount ISO image
-          command: >
-            sudo mount -o loop metalk8s.iso
-            /srv/scality/metalk8s-%(prop:metalk8s_version)s
-          haltOnFailure: true
-      - ShellCommand:
-          name: Create bootstrap configuration file
-          command: |
-            sudo bash << EOF
-            mkdir -p /etc/metalk8s
-            cat > /etc/metalk8s/bootstrap.yaml << END
-            apiVersion: metalk8s.scality.com/v1alpha2
-            kind: BootstrapConfiguration
-            networks:
-              controlPlane: 10.100.0.0/16
-              workloadPlane: 10.100.0.0/16
-            ca:
-              minion: $(hostname)
-            apiServer:
-              host: $(ip route get 10.100.0.0 | awk '/10.100.0.0/{ print $6 }')
-            archives:
-              - /srv/scality/metalk8s-%(prop:metalk8s_version)s
-            END
-            EOF
-      - ShellCommand:
-          name: Start the bootstrap process
-          command: >
-            sudo bash
-            /srv/scality/metalk8s-%(prop:metalk8s_version)s/bootstrap.sh
-            --verbose
-          haltOnFailure: true
-      - ShellCommand:
-          name: Install kubectl for running tests
-          command: >
-            sudo yum install -y kubectl --disablerepo=*
-            --enablerepo=metalk8s-kubernetes
-      - ShellCommand:
-          name: Run tests locally
+          <<: *local_tests
+          name: Run slow tests locally
           env:
-            ISO_MOUNTPOINT: >
-              /srv/scality/metalk8s-%(prop:metalk8s_version)s
-          command: >
-            tox -e tests-local --
-            -m "post and ci and not multinode and not slow" &&
-            tox -e tests-local --
-            -m "post and ci and not multinode and slow"
-          haltOnFailure: true
+            <<: *_env_local_tests
+            PYTEST_FILTERS: "post and ci and not multinodes and slow"
+      # --- Collect logs ---
+      - ShellCommand: *collect_sosreport
       - ShellCommand:
-          name: Collect logs using sosreport
-          command: >
-            sudo sosreport --all-logs
-            -o metalk8s -kmetalk8s.podlogs=True
-            -o containerd -kcontainerd.all=True -kcontainerd.logs=True
-            --batch --tmp-dir /var/tmp &&
-            sudo chown eve:eve /var/tmp/sosreport*
-          alwaysRun: true
-      - ShellCommand:
-          name: Copy sosreport to correct directory structure
-          command: >
-            mkdir -p sosreport/sosreport/single-node &&
-            cp /var/tmp/sosreport* sosreport/sosreport/single-node
-          alwaysRun: true
-      - Upload:
-          name: upload artifacts
-          source: sosreport
-          alwaysRun: true
-      - ShellCommand:
-          name: Debug step - wait 1 hour before allowing resource destruction
-          timeout: 3600
-          command: sleep 3600
-          doStepIf: false
-          alwaysRun: true
+          <<: *copy_report_artifacts
+          env:
+            DEST_DIR: sosreport/sosreport/single-node-downgrade
+      - Upload: *upload_report_artifacts
+      - ShellCommand: *wait_debug
 
   multiple-nodes:
     worker:
-      type: openstack
-      image: CentOS-7-x86_64-GenericCloud-1809.qcow2
+      <<: *single_node_worker
       flavor: m1.medium
       path: eve/workers/openstack-multiple-nodes
     steps:
@@ -299,7 +374,7 @@ stages:
           name: Spawn openstack virtual infra
           command: terraform apply -auto-approve
           workdir: build/eve/workers/openstack-multiple-nodes/terraform/
-          env: &terraform_spawn_multiple_nodes
+          env: &_env_terraform
             OS_AUTH_URL: "%(secret:scality_cloud_auth_url)s"
             OS_REGION_NAME: "%(secret:scality_cloud_region)s"
             OS_USERNAME: "%(secret:scality_cloud_username)s"
@@ -397,19 +472,23 @@ stages:
             tar cfp - tox.ini VERSION tests/ buildchain/buildchain/versions.py
             | ssh -F $SSH_CONFIG bastion '(mkdir metalk8s; cd "$_"; tar xf -)'
       - ShellCommand:
-          name: Run tests on the bastion
-          # yamllint disable rule:line-length
-          command: >
-            ssh -F ssh_config bastion --
-            'cd metalk8s &&
-            export SSH_CONFIG_FILE=/home/centos/ssh_config &&
-            export ISO_MOUNTPOINT=/var/tmp/metalk8s &&
-            export TEST_HOSTS_LIST=bootstrap &&
-            tox -e tests -- -m "ci and not slow" &&
-            tox -e tests -- -m "ci and slow"'
-          # yamllint enable rule:line-length
-          workdir: build/eve/workers/openstack-multiple-nodes/terraform/
-          haltOnFailure: true
+          <<: *bastion_tests
+          name: Run installation scenarii on the bastion
+          env:
+            <<: *_env_bastion_tests
+            PYTEST_FILTERS: "install and ci and multinodes"
+      - ShellCommand:
+          <<: *bastion_tests
+          name: Run fast tests on the bastion
+          env:
+            <<: *_env_bastion_tests
+            PYTEST_FILTERS: "post and ci and not slow"
+      - ShellCommand:
+          <<: *bastion_tests
+          name: Run slow tests on the bastion
+          env:
+            <<: *_env_bastion_tests
+            PYTEST_FILTERS: "post and ci and slow"
       - ShellCommand:
           name: Generate sosreport on every machine
           env:
@@ -437,16 +516,11 @@ stages:
               sosreport/sosreport/multi-node/$host-sosreport.tar.xz
             done
           alwaysRun: true
-      - Upload:
-          name: Upload sosreport tarballs
-          source: sosreport
-          alwaysRun: true
+      - Upload: *upload_report_artifacts
       - ShellCommand:
-          name: Debug step - wait 4 hours before allowing resource destruction
+          <<: *wait_debug
           timeout: 14400
           command: sleep 14400
-          alwaysRun: true
-          doStepIf: false
       - ShellCommand:
           name: Destroy openstack virtual infra
           command: |-
@@ -454,6 +528,6 @@ stages:
                terraform destroy -auto-approve && break
             done;
           workdir: build/eve/workers/openstack-multiple-nodes/terraform/
-          env: *terraform_spawn_multiple_nodes
+          env: *_env_terraform
           alwaysRun: true
           sigtermTime: 600
