ci/ui: Wait for sidecar application to be ready
We had some flakies where the sidecar nginx wouldn't start soon enough.
This should avoid such issues in the future.

See: #2878

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -1090,6 +1090,20 @@ stages:
             done
           haltOnFailure: true
       - ShellCommand:
+          name: Wait for application to be available
+          command: |
+            bash -c '
+              attempts=0
+              until curl -Isfo /dev/null http://localhost:80/; do
+                (( attempts++ ))
+                if [ $attempts -gt 40 ]; then
+                  >&2 echo "Failed to reach application after 2 minutes"
+                  exit 1
+                fi
+                sleep 3
+              done
+            '
+      - ShellCommand:
           name: Run all UI integration tests
           workdir: build/ui
           env:
