eve: Check status code when retrieving ISO images
In CI when we retrieve ISO images we do not fail properly if, for
example the ISO image does not exists (404 Not found).
So check the status code of the curl request.

NOTE: We do not use `-f/--fail` of curl as we do not want to retry if we
get a 404 for example

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -251,7 +251,16 @@ models:
           if [ $(( $i % 10 )) -eq 1 ]; then
             echo "Attempt $i out of ${MAX_ATTEMPTS}"
           fi
-          curl -L -s -XGET -o "${out_path}" "${in_url}" && exit
+          status_code=$(curl -L -s -XGET -o "${out_path}" "${in_url}" --write-out "%{http_code}")
+          case "$status_code" in
+              200)
+                  exit
+                  ;;
+              404)
+                  echo "Could not retrieve $FILE_SOURCE: $status_code" >&2
+                  exit 1
+                  ;;
+          esac
           sleep 2
         done
         echo "Could not retrieve $FILE_SOURCE after $MAX_ATTEMPTS attempts" >&2
