ci: Add retrying logic for large artifacts
Sometimes, it seems the artifacts service returns an empty content,
yielding a returncode 18 from `curl`. We retry the call until we hit a
maximum number of retries, to alleviate such situations.

diff --git a/eve/main.yml b/eve/main.yml
--- a/eve/main.yml
+++ b/eve/main.yml
@@ -104,23 +104,36 @@ models:
         DEST_DIR: sosreport/sosreport
       command: mkdir -p "${DEST_DIR}" && cp /var/tmp/sosreport* "${DEST_DIR}"
       alwaysRun: true
-  - ShellCommand: &retrieve_iso
-      name: Retrieve ISO image
-      env:
+  - ShellCommand: &retrieve_iso_checksum
+      name: Retrieve ISO image checksum
+      env: &_env_retrieve_artifact
         BASE_URL: "%(prop:artifacts_private_url)s"
         DEST_DIR: "."
-      command: >
-        curl -s -XGET -o "${DEST_DIR}/metalk8s.iso" "${BASE_URL}/metalk8s.iso"
-      haltOnFailure: true
-      # Increase default timeout for ISOs, as artifacts may be too slow
-      timeout: 2400
-  - ShellCommand: &retrieve_iso_checksum
-      <<: *retrieve_iso
-      name: Retrieve ISO image checksum
       command: >
         curl -s -XGET -o "${DEST_DIR}/SHA256SUM" "${BASE_URL}/SHA256SUM"
       # Three minutes should be enough for this small file
       timeout: 180
+  - ShellCommand: &retrieve_iso
+      name: Retrieve ISO image
+      env: &_env_retrieve_artifact_retry
+        <<: *_env_retrieve_artifact
+        MAX_ATTEMPTS: "300" # retry every 2 seconds for 10 minutes total
+      command: |
+        bash -c '
+        in_url="${BASE_URL}/metalk8s.iso"
+        out_path="${DEST_DIR}/metalk8s.iso"
+        for ((i=1;i<=MAX_ATTEMPTS;i++)); do
+          if [ $(( $i % 10 )) -eq 1 ]; then
+            echo "Attempt $i out of ${MAX_ATTEMPTS}"
+          fi
+          curl -s -XGET -o "${out_path}" "${in_url}" && exit
+          sleep 2
+        done
+        echo "Could not retrieve ISO after ${MAX_ATTEMPTS} attempts" >&2
+        exit 1'
+      haltOnFailure: true
+      # Increase default timeout for ISOs, as artifacts may be too slow
+      timeout: 2400
   - ShellCommand: &create_mountpoint
       name: Create mountpoint
       env:
@@ -375,20 +388,22 @@ stages:
       - ShellCommand: *setup_cache
       - ShellCommand: *ssh_ip_setup
       # --- Get ISO for version N ---
-      - ShellCommand: *retrieve_iso
       - ShellCommand: *retrieve_iso_checksum
+      - ShellCommand: *retrieve_iso
       - ShellCommand: *check_iso_checksum
       # --- Get ISO for version N-1 ---
+      - ShellCommand: &retrieve_prev_iso_checksum
+          <<: *retrieve_iso_checksum
+          env: &_env_previous_artifact
+            DEST_DIR: "/tmp"
+            BASE_URL: "%(prop:artifacts_private_url)s/pre"
+          name: Retrieve previous ISO image checksum
       - ShellCommand: &retrieve_prev_iso
           <<: *retrieve_iso
           name: Retrieve previous ISO image
-          env: &_env_previous
-            DEST_DIR: "/tmp"
-            BASE_URL: "%(prop:artifacts_private_url)s/pre"
-      - ShellCommand: &retrieve_prev_iso_checksum
-          <<: *retrieve_iso_checksum
-          name: Retrieve previous ISO image checksum
-          env: *_env_previous
+          env:
+            <<: *_env_previous_artifact
+            MAX_ATTEMPTS: "300"
       - ShellCommand: &check_prev_iso_checksum
           <<: *check_iso_checksum
           name: Check previous ISO image with checksum
@@ -479,12 +494,12 @@ stages:
       - ShellCommand: *setup_cache
       - ShellCommand: *ssh_ip_setup
       # --- Get ISO for version N ---
-      - ShellCommand: *retrieve_iso
       - ShellCommand: *retrieve_iso_checksum
+      - ShellCommand: *retrieve_iso
       - ShellCommand: *check_iso_checksum
       # --- Get ISO for version N-1 ---
-      - ShellCommand: *retrieve_prev_iso
       - ShellCommand: *retrieve_prev_iso_checksum
+      - ShellCommand: *retrieve_prev_iso
       - ShellCommand: *check_prev_iso_checksum
       # --- Prepare for Bootstrap in version N-1 ---
       - ShellCommand:
