.github: Migrate ui integrations tests to GitHub actions

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -135,7 +135,7 @@ jobs:
           # Fake that we are building in a ReadTheDocs environment
           READTHEDOCS: "True"
         run: tox --workdir /tmp/tox -e docs -- html
-      - name: Copy generated docs for ReadTheDocs 
+      - name: Copy generated docs for ReadTheDocs
         run: mkdir -p artifacts/docs/readthedocs && cp -r docs/_build/* artifacts/docs/readthedocs/
       - name: Build documentation with Scality theme
         run: rm -rf docs/_build && tox --workdir /tmp/tox -e docs -- html
@@ -193,16 +193,31 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ inputs.ref }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Install node
+        uses: actions/setup-node@v2
+        with:
+          node-version: "16"
+      - name: Cache node modules
+        id: cache-npm
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-node-modules
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
       - name: Install UI dependencies
-        # TODO: Check if we cannot use another Docker or move this one out of eve directory
         run: |
-          docker build ui -t ui-builder -f eve/workers/pod-unit-tests-ui/ui.Dockerfile
-          docker run -t --rm --entrypoint /bin/sh -v $(pwd)/ui:/tmp ui-builder -c "npm ci --prefer-offline --no-audit --legacy-peer-deps --unsafe-perm --no-optional"
+          cd ui
+          npm ci --prefer-offline --no-audit --legacy-peer-deps --unsafe-perm --no-optional
       - name: Run all UI unit tests
         run: |
-          docker run -t --rm --entrypoint /bin/sh -v $(pwd)/ui:/tmp ui-builder -c "npm run test:nowatch --no-update-notifier"
+          cd ui
+          npm run test:nowatch --no-update-notifier
       - name: Prepare artifacts
         run: mkdir -p "artifacts/ui" && mv ui/junit artifacts/ui/
       - name: Upload artifacts
@@ -221,16 +236,31 @@ jobs:
         uses: actions/checkout@v3
         with:
           ref: ${{ inputs.ref }}
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+      - name: Install node
+        uses: actions/setup-node@v2
+        with:
+          node-version: "16"
+      - name: Cache node modules
+        id: cache-npm
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-node-modules
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
       - name: Install UI dependencies
-        # TODO: Check if we cannot use another Docker or move this one out of eve directory
         run: |
-          docker build ui -t ui-builder -f eve/workers/pod-unit-tests-ui/ui.Dockerfile
-          docker run -t --rm --entrypoint /bin/sh -v $(pwd)/shell-ui:/tmp ui-builder -c "npm ci --prefer-offline --no-audit --legacy-peer-deps -d"
+          cd shell-ui
+          npm ci --prefer-offline --no-audit --legacy-peer-deps -d
       - name: Run all Shell UI unit tests
         run: |
-          docker run -t --rm --entrypoint /bin/sh -v $(pwd)/shell-ui:/tmp ui-builder -c "npm run test --no-update-notifier"
+          cd shell-ui
+          npm run test --no-update-notifier
 
   unit_tests_crd_client_generator:
     runs-on: ubuntu-20.04
@@ -363,11 +393,159 @@ jobs:
       - name: Run all lib_alert_tree unit tests
         run: poetry run pytest -vv
 
-  # TODO: intergration_tests_ui
+  build_integration_container_nginx:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.ref }}
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+      - name: Install node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      - name: Cache node modules
+        id: cache-npm
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-node-modules
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+      - name: Install Shell UI dependencies
+        run: |
+          cd shell-ui
+          npm ci --legacy-peer-deps
+      - name: Build Shell UI
+        run: |
+          cd shell-ui
+          npm run build
+      - name: Install UI dependencies
+        run: |
+          cd ui
+          npm ci --legacy-peer-deps --no-optional
+      - name: Build UI
+        run: |
+          cd ui
+          npm run build
+      - name: Prepare Services Volumes
+        run: |
+          mkdir -p service
+          mkdir -p service/shell
+          cp -r ui/build/* service/
+          cp -r ui/build/.well-known service/.well-known
+          cp -r shell-ui/build/* service/shell/
+      - name: Build container with nginx configuration for integration tests
+        run: |
+          cat > Dockerfile <<EOF
+          FROM nginx:alpine
+          COPY ui/standalone-nginx.conf /etc/nginx/conf.d/default.conf
+          ADD service /usr/share/nginx/html
+          EOF
+      - name: Login to Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - uses: docker/build-push-action@v2
+        with:
+          push: true
+          file: Dockerfile
+          context: .
+          tags: ghcr.io/${{ github.repository_owner }}/metalk8s-nginx-integration-tests:${{ github.sha }}
+
+  integration_tests_ui:
+    runs-on: ubuntu-20.04
+    needs:
+      - build_integration_container_nginx
+    services:
+      app:
+        image: ghcr.io/${{ github.repository_owner }}/metalk8s-nginx-integration-tests:${{ github.sha }}
+        credentials:
+          username: ${{ github.repository_owner }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+        ports:
+          - 80:80
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ inputs.ref }}
+      - name: Install node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      - name: Cache node modules
+        id: cache-npm
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-node-modules
+        with:
+          # npm cache files are stored in `~/.npm` on Linux/macOS
+          path: ~/.npm
+          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-build-${{ env.cache-name }}-
+            ${{ runner.os }}-build-
+            ${{ runner.os }}-
+      - name: Install Cypress and its dependencies
+        run: |
+          cd ui
+          PKGS="har-validator cypress cypress-cucumber-preprocessor cypress-wait-until @testing-library/cypress"
+          for pkg in $PKGS; do
+            npm install --no-save --no-package-lock --legacy-peer-deps $pkg@$(node -p \
+              -e "require('./package-lock.json').dependencies['$pkg'].version" \
+            ) || exit 1
+          done
+      - name: Wait for application to be available
+        run: |
+          bash -c '
+            attempts=0
+            until curl -Isfo /dev/null http://localhost/; do
+              (( attempts++ ))
+              if [ $attempts -gt 100 ]; then
+                >&2 echo "Failed to reach application after 5 minutes"
+                exit 1
+              fi
+              sleep 3
+            done
+          '
+      - name: Run all UI integration tests
+        env:
+          CYPRESS_BASE_URL: http://localhost
+        run: |
+          cd ui
+          rm -rf babel.config.js
+          npm run test:integration --no-update-notifier
+      - name: Prepare upload folder
+        if: always()
+        run: |
+          mkdir -p upload/ui/cypress
+          mv cypress/screenshots upload/ui/cypress/screenshots || true
+          mv cypress/videos upload/ui/cypress/videos || true
+          mv junit upload/ui || true
+      - name: Upload artifacts
+        if: always()
+        uses: scality/action-artifacts@v3
+        with:
+          method: upload
+          url: https://artifacts.scality.net
+          user: ${{ secrets.ARTIFACTS_USER }}
+          password: ${{ secrets.ARTIFACTS_PASSWORD }}
+          source: upload
 
   write-final-failed-status:
     runs-on: ubuntu-20.04
-    needs: 
+    needs:
       - build
       - build-shell-ui
       - docs
@@ -379,7 +557,7 @@ jobs:
       - unit_tests_storage_operator
       - unit_tests_salt
       - unit_tests_lib_alert_tree
-      #- integration_tests_ui
+      - integration_tests_ui
     if: failure()
     steps:
       - name: Checkout
@@ -401,7 +579,7 @@ jobs:
 
   write-final-success-status:
     runs-on: ubuntu-20.04
-    needs: 
+    needs:
       - build
       - build-shell-ui
       - docs
@@ -413,7 +591,7 @@ jobs:
       - unit_tests_storage_operator
       - unit_tests_salt
       - unit_tests_lib_alert_tree
-      #- integration_tests_ui
+      - integration_tests_ui
     if: success()
     steps:
       - name: Checkout
